environment:
  matrix:
    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64


install:
  - set "PATH=%PYTHON%;%PYTHON%/Scripts;%PYTHON%/Library/bin;%PATH%"
  - set "PYTHONPATH=%PYTHONPATH%;C:/projects/hpic"
  - python -m pip install --upgrade pip
  - pip install numpy
  - pip install scipy
  - pip install scikit-learn
  - pip install pandas
  - pip install pyopenms
  - pip install hdbscan
  - pip install wget

build_script:

  - python setup.py build

test_script:

  -   python C:/projects/hpic/hpic/tests/test_fileio.py
  -   python C:/projects/hpic/hpic/tests/test_mspd.py
  -   python C:/projects/hpic/hpic/tests/test_hpic.py